version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ..:/project:delegated
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    environment:
      LANG: "C.UTF-8"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "mysql-test"
      TZ: Tokyo/Asia
  redis:
    image: redis:alpine
